---
- name: Install Clickhouse.
  hosts: clickhouse
  become: true
  roles:
    - clickhouse

- name: Install Vector.
  hosts: vector
  become: true
  roles:
    - vector

- name: Install Lighthouse.
  hosts: lighthouse
  become: true
  roles:
    - lighthouse