resource "local_file" "compose" {
  content = <<-DOC
    # Docker-compose containing variable values from Terraform.
    # Generated by Terraform.
    version: "3"
    services:
      teamcity-agent:
        image: jetbrains/teamcity-agent 
        volumes:
          - ~/teamcity/agent/:/opt/stack/conf 
        environment:
          SERVER_URL: "http://${yandex_compute_instance.ts-server.network_interface.0.nat_ip_address}:8111"
    DOC
  filename = "../ansible/stack2/docker-compose.yaml"

  depends_on = [
    yandex_compute_instance.ts-server
  ]
}