resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    ---
    all:
      hosts:
        ts-server:
          ansible_host: ${yandex_compute_instance.ts-server.network_interface.0.nat_ip_address}
        ts-agent:
          ansible_host: ${yandex_compute_instance.ts-agent.network_interface.0.nat_ip_address}
        nexus-01:
          ansible_host: ${yandex_compute_instance.nexus.network_interface.0.nat_ip_address}
      children:
        ts:
          children:
            ts-servers:
              hosts:
                ts-server:
            ts-agents:
              hosts:
                ts-agent:
        nexus:
          hosts:
            nexus-01:
      vars:
        ansible_connection_type: paramiko
        ansible_user: almalinux
        ansible_port: 22
        ansible_ssh_private_key_file: ../../../keys/id_rsa
    DOC
  filename = "../ansible/hosts.yml"

  depends_on = [
    yandex_compute_instance.ts-server,
    yandex_compute_instance.ts-agent,
    yandex_compute_instance.nexus
  ]
}
