version: '3.5'
services:
  postgres_new:
    container_name: psql2
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data_new:/var/lib/postgresql/data
      - ./backup:/data/backup/postgres
    ports:
      - "5433:5432"
    restart: always
    networks:
      - psql1

networks:
  psql1:
    driver: bridge