{
 "title": "Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "Load 1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "Load 5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "Load 15"
    }
   ]
  },
  {
   "title": "MemFree MB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / (1024 * 1024)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "MemFree %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} / (1024 * 1024 * 1024)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk Free %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"}) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}