ISO = "spox/ubuntu-arm"
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "./ansible/inventory"

servers = [
      {
        :hostname => HOST_PREFIX + "1" + DOMAIN,
        :ssh_host => "20011",
        :ssh_vm => "22",
        :ram => 1024,
        :core => 1
      }
]
Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: false
    servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
        node.vm.box_version = "1.0.0"
        node.vm.box = ISO
        node.vm.hostname = machine[:hostname]
        node.vm.network :forwarded_port, guest: machine[:ssh_vm],
host: machine[:ssh_host]
        node.vm.provider "vmware_desktop" do |v|
          v.gui = true
          v.vmx["memsize"] = machine[:ram]
          v.vmx["numvcpus"] = machine[:core]
        end
        node.vm.provision "ansible" do |setup|
          setup.inventory_path = INVENTORY_PATH
          setup.playbook = "./ansible/provision.yml"
          setup.become = true
          setup.extra_vars = { ansible_user: 'vagrant' }
        end
      end
    end
end
  