apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    env:
    - name: HTTP_PORT
      value: "1181"
    - name: HTTPS_PORT
      value: "11444"
    ports:
    - containerPort: 1181
      name: http-port
    - containerPort: 11444
      name: https-port
    resources:
      requests:
        cpu: "1m"
        memory: "20Mi"
      limits:
        cpu: "10m"
        memory: "20Mi"