apiVersion: v1 
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  ports:
  - name: http-nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-nginx
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: task2