version: '3.5'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
    volumes:
      - ./data:/var/lib/mysql
      - ../test_data:/backup
    ports:
      - 3306:3306
    restart: always