resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    clickhouse
    vector
    lighthouse

    [clickhouse]
    ${yandex_compute_instance.clickhouse.hostname} ansible_host=${yandex_compute_instance.clickhouse.network_interface.0.nat_ip_address}

    [vector]
    ${yandex_compute_instance.vector.hostname} ansible_host=${yandex_compute_instance.vector.network_interface.0.nat_ip_address}

    [lighthouse]
    ${yandex_compute_instance.lighthouse.hostname} ansible_host=${yandex_compute_instance.lighthouse.network_interface.0.nat_ip_address}

    [all:vars]
    ansible_user=almalinux
    ansible_port=22
    ansible_ssh_private_key_file=../../../keys/id_rsa
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.clickhouse,
    yandex_compute_instance.vector,
    yandex_compute_instance.lighthouse
  ]
}