apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-deployment
  labels:
    app: task1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8433"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8433
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: multi-deployment-svc
spec:
  ports:
  - name: http-nginx
    port: 9001
    protocol: TCP
    targetPort: 80
  - name: http-multitool
    port: 9002
    protocol: TCP
    targetPort: 8080
  selector:
    app: task1