global:
  scrape_interval: 15s 

scrape_configs:

  - job_name: 'security'
    metrics_path: /sec_mt
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'uploader'
    metrics_path: /up_mt
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'storage'
    metrics_path: /minio_mt
    scheme: http
    static_configs:
    - targets: ['gateway:8080']