---
  - src: https://github.com/vi-htor/clickhouse.git
    scm: git
    version: "0.1"
    name: clickhouse 

  - src: https://github.com/vi-htor/vector.git
    scm: git
    version: "0.1"
    name: vector 

  - src: https://github.com/vi-htor/lighthouse.git
    scm: git
    version: "0.1"
    name: lighthouse 